### ISSUE TITLE
time for internal redirects

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#143]
Over on Gittip I'm using an [internal redirect](https://github.com/zetaweb/www.gittip.com/blob/602e70fd23d76da37107f05575f60ee6a5d1c7c3/www/on/twitter/associate#L76) to vary the content served during social auth sign in flow (if the social account is connected to another gittip account then we interject a merge UI). Seems like that feature should be upstreamed.

**Comment by pjz** [comment]
After quite a long hiatus (2 years? really?) I went to look at this again and, given the use of algorithm.py, am now unsure how it should be implemented.  Ideas?

**Comment by Changaco** [comment]
I'm not sure internal redirects are a good idea, in fact the one that started this issue no longer exists, I got rid of it in https://github.com/gratipay/gratipay.com/pull/3226.

**Comment by pjz** [comment]
I'm willing to Just Say No to internal redirects :)

**Comment by whit537** [comment]
Closing for @pjz. Reopen if you want this.
