### ISSUE TITLE
redirect *from* trailing slash

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#299]
Right now we redirect *to* trailing slash, so if you hit `/foo/bar` and `bar` is a directory, then we redirect to `/foo/bar/`. I propose that we switch that behavior around, so that `/foo/bar/` always redirects to `/foo/bar`.

**Comment by whit537** [comment]
Action here is to add this to `aspen.utils`:

```
def redirect_from_trailing_slash(request):
    path = request.line.uri.path.raw
    if path.endswith('/'):
        request.redirect(path[:-1]) # + qs
```

With a docstring for how to use it: `algorithm.insert_after('dispatch_request_to_filesystem', redirect_from_trailing_slash)`, and then use `foo.spt` instead of `foo/index.spt` for indices.

**Comment by pjz** [comment]
And note that foo.spt *must* exist, or else you'll get a nasty redirect loop.

**Comment by whit537** [comment]
Possibly we can inspect `dispatch_result` inside `redirect_from_trailing_slash` to avoid the redirect loop and give a 404 instead.

**Comment by whit537** [comment]
The result I want is to end up on `/foo` with a `404`.

**Comment by whit537** [comment]
I.e., I *don't* want to be on `/foo/` with a `404`.

**Comment by whit537** [comment]
Another idea: subclass `Response` and then raise `RedirectFromTrailingSlash`, catch that in `redirect_from_trailing_slash`.

**Comment by whit537** [comment]
How can we use the dispatch table to drive this?

**Comment by whit537** [comment]
[January 2015 call](https://www.youtube.com/watch?v=8blwV35gDns)

**Comment by whit537** [comment]
Something like ... ?

```python
def redirect_from_trailing_slash(request, exception=None):
    if exception is not None and not isinstance(exception, RedirectToTrailingSlash):
        return
    path = request.line.uri.path.raw
    if path.endswith('/'):
        request.redirect(path[:-1]) # + qs
```

**Comment by pjz** [comment]
I think the solution is, as you mentioned, to subclass `Response` into a `RedirectFromTrailingSlash` class that gets raised on line 348 of the dispatcher.  Then catch it in `redirect_from_trailing_slash` and turn it into a 404 (since it only happens if `/foo` is requested but there's no `/foo.spt` but is a `/foo/`).  So more like:
```
def redirect_from_trailing_slash(request, exception=None):
    if exception is not None:
        if isinstance(exception, RedirectToTrailingSlash):
            raise FileNotFound
        return
    path = request.line.uri.path.raw
    if path.endswith('/'):
        request.redirect(path[:-1]) # + qs
```

**Comment by pjz** [comment]
Whatever the solution, it can now be pretty easily implemented in the algorithm.
