### ISSUE TITLE
do away with configure-aspen.py

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#373]
Now that we're a framework and not an app server, we don't need a special way to exec python code to configure your site. Just use Python! This means that if want to use Python to configure your site you'll need to unroll one of the following, depending on your deployment scenario:

 - `aspen/wsgi.py`
 - `aspen/__main__.py`
 - `fcgi_aspen.py`

[call](https://www.youtube.com/watch?v=1kKh2URbJvs)

**Comment by pjz** [comment]
Query: If we do this, do we still need a `project_root` at all? or can we run just given a `www_root` ?

**Comment by whit537** [comment]
> [C]an we run just given a `www_root`?

Worth considering. Even if we scrap `sys.path` modifications, you'd still get cwd on `sys.path` for the `python -m aspen` case. Not sure about behavior under gunicorn, etc. For heavier-duty setups you're installing proper modules in a virtualenv anyway.

We do resolve templates bases/includes with `project_dir` in aspen-jinja2. What would we do there?

Error simplates we've talked about: #141.

**Comment by pjz** [comment]
Add a knob to `aspen-jinja2` to set that; or do all templating systems have a template base, so we should make a generic `template_root` for it?
