### ISSUE TITLE
stop taking configuration from argv

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#374]
We're not an app server anymore, so we can stop configuring from the command line.

**Comment by techtonik** [comment]
I am not you sure about this, because going from:
```
aspen_config = [
    '--www_root=www/',
    '--project_root=.'
]
```
to
```
aspen_config = {
    'www_root':'www/',
    'project_roo':'.',
}
```
Is not more readable.

**Comment by whit537** [comment]
Honestly I'm not sold on this either. From an API perspective I think it's more natural to simply modify attributes on the `website` object as we've been doing. This should work (see #53):

```python
website.www_root = "foo"
```

**Comment by whit537** [comment]
As should this:

```
class GratipayCom(Website):
    www_root = "foo"
```

**Comment by techtonik** [comment]
> website.www_root = "foo"

I was unable to find this way when I needed it. Interesting side effect that by sticking to `--www_root=` as format for specifying option, it is easy to grep all places where the option is set and filter all places where the option is used.

**Comment by techtonik** [comment]
I guess that's the reason OOP folks are obsessed with getters and setters.

**Comment by techtonik** [comment]
But `--www_root` is more concise than `set_www_root_option()`

**Comment by techtonik** [comment]
And also doesn't need a ton of methods.

**Comment by pjz** [comment]
This was done in #455, right?

**Comment by whit537** [comment]
Yup!
