### ISSUE TITLE
include Response class in default simplate context

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#402]
Suggested by @techtonik at https://github.com/gratipay/gratipay.com/commit/4d7d0dc24302e3209a70cd350269f677571f147b#commitcomment-8820613. It's definitely a common error, `NameError: name 'Response' is not defined`. This usually lies along error paths, and error paths are undertested as a rule, so it's a bug that lurks waiting to mask *real* errors.

**Comment by pjz** [comment]
This was done when we moved to passing around all of algorithm state, yes?

**Comment by whit537** [comment]
We're moving towards more explicitness with simplate contexts: #30. Closing.
