### ISSUE TITLE
untangle content negotiation from rendering

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#416]
Knowing the content type of the response being built would help with choosing escaping functions during i18n. [IRC](https://botbot.me/freenode/gratipay/2015-02-09/?msg=31581218&page=1)

**Comment by whit537** [comment]
cc: @Changaco

**Comment by whit537** [comment]
Basically the idea is to move the `response.body = render(context)` call out of the `get_response` call:
https://github.com/gratipay/aspen-python/blob/0.36/aspen/resources/simplate.py#L188-L227.

**Comment by whit537** [comment]
But we also need a chance to inspect the result of content negotiation before the body is rendered, which indicates that this should be pushed up into an algorithm function. That gets static resources involved.

**Comment by pjz** [comment]
Is this still desired? reading the old IRC logs I remember not fully understanding the desire then, much less now.   Simplates' whole existence is rendering, it makes no sense to pull that out of the simplate...

**Comment by Changaco** [comment]
The idea was to resolve the media type earlier in a separate step and put that information in the state so that custom algorithm functions and the second page of the simplate have access to it.

**Comment by pjz** [comment]
and by 'resolve the media type' you mean what? the requested media type (Accept: header) ? or the result of mimeparse(accept_header, types_accepted_by_this_simplate) ?

**Comment by Changaco** [comment]
Yes, I mean the result of `mimeparse`, [that code](https://github.com/gratipay/aspen-python/blob/aa4314d2f349e55c08ec1cc0e80e569659c1f192/aspen/simplates/__init__.py#L147-L160).

**Comment by pjz** [comment]
...can't you call `mimeparse.best_match(accept, simplate.available_types)` yourself?  Should that be refactored into something like `simplate.best_match(accept)` ?

**Comment by Changaco** [comment]
> can't you call `mimeparse.best_match(accept, simplate.available_types)` yourself?

I wouldn't consider that a clean solution.

> Should that be refactored into something like `simplate.best_match(accept)` ?

Yes.
