### ISSUE TITLE
make simplates easier to instantiate

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#417]
Right now it takes a `website` object to instantiate a simplate (via resources.get). Can we make this simpler, to support things like https://github.com/gratipay/gratipay.com/blob/1778/gratipay/utils/emails.py?

**Comment by pjz** [comment]
I think this will fall out of refactoring simplates into their own module.

**Comment by pjz** [comment]
Done in #481.  Reopen if you think I'm wrong.
