### ISSUE TITLE
figure out what changed with content negotiation in 0.37

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#422]
When we deployed 0.37 for Gratipay we had some simplates that switched from serving HTML to serving JSON. We haven't captured an Accept header for it yet.

**Comment by whit537** [comment]
Background: https://github.com/gratipay/gratipay.com/issues/3210 and https://github.com/gratipay/gratipay.com/pull/3213.

**Comment by Changaco** [comment]
A new function named `extract_accept_from_request` was added to the website algorithm in fc7dd636151d6f97b8d677dc122ad27fa977bc47.

**Comment by pjz** [comment]
Does this need more docs somewhere?

**Comment by Changaco** [comment]
A note in `Changelog.md` would have been useful. A safe way to patch the website algorithm would be even better: https://github.com/gratipay/algorithm.py/issues/5.

**Comment by whit537** [comment]
> A note in `Changelog.md` would have been useful.

+1
