### ISSUE TITLE
hold call for June, 2015

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#432]
Ready, @pjz et al.?

**Comment by pjz** [comment]
Yup.

**Comment by whit537** [comment]
Sorry, otp ... brb

**Comment by pjz** [comment]
if you have another call at 10, should we bother?

**Comment by whit537** [comment]
Yes, let's ... just got back ...

https://plus.google.com/hangouts/_/hoaevent/AP36tYeWcU2S--bTAFqdcxc-cEh986azDQG8To4hno8-datTGceU9g

**Comment by whit537** [comment]
!m @pjz 

https://www.youtube.com/watch?v=fiuaKKjzyrA
