### ISSUE TITLE
aspen.resources API break not documented

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen-python#436]
resources.get() changed in 0.35 from `def get(request):`
https://github.com/gratipay/aspen-python/blob/0.34/aspen/resources/__init__.py#L160
to `def get(website, fspath):`
https://github.com/gratipay/aspen-python/blob/0.35/aspen/resources/__init__.py#L160

With no traces in https://github.com/gratipay/aspen-python/blob/master/Changelog.md#035---released-thu-oct-30-2014-by-whit537

At the very least I expected major version bump. At maximum - migration guide.

**Comment by pjz** [comment]
Two things: 

1) We haven't hit 1.0 so we consider all APIs still unstable and subject to change

2) I'm not sure that aspen.resources.get() is really a 'public' API anyway: it's used internally, but as a web framework I think Aspen's API is more about the Website object and the things that get used in simplates.  I'd love to hear arguments on the other side, though!

**Comment by techtonik** [comment]
@pjz I tried to update Aspen for inside.gratipay.com and got some stacktrace on that. I can not continue, because I do not understand the error. I can repeat and post it here tomorrow, but maybe you can immediately say what was changed and needs to be fixed here.
https://github.com/gratipay/inside.gratipay.com/blob/1fc02bc111e4444f204b250066cae489f9a29a3d/configure-aspen.py

I think of Aspen as of pythonic PHP.

**Comment by pjz** [comment]
You're going to need to provide an error for any chance of help with this.

**Comment by techtonik** [comment]
@pjz it was answered here - https://github.com/gratipay/inside.gratipay.com/pull/263#issuecomment-113294068 and there is anohter trace at https://github.com/gratipay/inside.gratipay.com/pull/263#issuecomment-113296723 which didn't occur with previous version.

**Comment by whit537** [comment]
@techtonik Make a PR against Changelog, ya?

**Comment by techtonik** [comment]
@whit537 I don't know what to write there. I don't know what is `nav.py` doing and for the moment there are other things I am researching. Changelog may not be the best place for it. Something more user level like https://mercurial.selenic.com/wiki/UpgradeNotes with no distracting details.

**Comment by pjz** [comment]
`nav.py` isn't part of aspen.  Gratipay != Aspen.

**Comment by techtonik** [comment]
`nav.py` may use Aspen API that apparently become broken.

**Comment by pjz** [comment]
See my first comment.

**Comment by techtonik** [comment]
Then why maintain changelog at all?

**Comment by techtonik** [comment]
And if that's an internal API, shouldn't it be prefixed with _?
