### ISSUE TITLE
Add website.run() method

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen-python#441]
To avoid writing this for every app:
```
#!/usr/bin/env python
"""
The main script to start website for development,
which also exports WSGI application for production.
"""

from aspen.website import Website

# by WSGI convention, we need to create webapp object
# and by default most WSGI servers look for 'application'
application = Website([])

if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    make_server('', 8000, application).serve_forever()
```

Do that:
```
#!/usr/bin/env python
"""
The main script to start website for development,
which also exports WSGI application for production.
"""
from aspen.website import Website

# by WSGI convention, we need to create webapp object
# and by default most WSGI servers look for 'application'
application = Website([])

if __name__ == '__main__':
    application.run()
```

**Comment by whit537** [comment]
Sure, but let's call it `rundev` to make it clear that it's not for production usage.

**Comment by techtonik** [comment]
Why it is not suitable for production? I don't see why it can not be used for small sites.

**Comment by whit537** [comment]
Well, you said it yourself in the docstring:

> The main script to start website for development,
which also exports WSGI application for production.

**Comment by techtonik** [comment]
Yes, but it is because Gratipay uses deployment through a Heroku defined process. I don't know which server do they prefer and why.

**Comment by whit537** [comment]
> I don't see why it can not be used for small sites.
> I don't know which server do they prefer and why.

The limitation with `wsgiref.make_server` is that it can only handle one request at a time. If you receive a request that takes one second to fulfill (maybe it does a lot with the database, or it's receiving a big upload), then the website won't be able to serve any other requests during that second. For production, this is acceptable for only hobby or otherwise very-low-traffic applications. How about `application.run_with_hobby_server()` or `run_with_toy_server`?

**Comment by techtonik** [comment]
> How about application.run_with_hobby_server() or run_with_toy_server?

Not a chance that I will remember those. Note that Flask provides `app.run()` method, but it uses more capable WSGI framework as dependency - werzeugh or something. Ok, let it be `rundev()`.

**Comment by whit537** [comment]
> it uses more capable WSGI framework as dependency - werzeugh or something

[werkzeug.serving](https://github.com/mitsuhiko/werkzeug/blob/c82e82ace368fefc0581bc0a700f1219cc4c79ca/werkzeug/serving.py) is also single-threaded and single-process.

> `rundev`

I don't like that `website.foo` confuses the role of the server with the role of the WSGI application. I would rather see `foo(website)`, like this:

```python
from aspen import publish, Website

website = Website()

if __name__ == '__main__':
    publish(website)
```

(P.S. Flask [doesn't use](http://flask.pocoo.org/docs/0.10/quickstart/) `application`. I'm not sure we need to, either)

**Comment by techtonik** [comment]
> werkzeug.serving is also single-threaded and single-process.

Then I see no reasons not to have `.run()` for convenience. If people would like to optimize the site for performance, they will use appropriate server like `gunicorn` etc. I thinks that's became pretty obvious in Python world, but could be explained once more in docstring.

> I don't like that website.foo confuses the role of the server with the role of the WSGI application.

I also don't like that Website inherits from Configuration instead of encapsulating it.

>     publish(website)

For me publishing means `compile and upload`, or `release draft to public`.

> (P.S. Flask doesn't use application. I'm not sure we need to, either)

It names it `app`, but it is WSGI application.
https://github.com/mitsuhiko/flask/blob/master/flask/app.py#L771

**Comment by pjz** [comment]
I vote no Website.run() because it moves WSGI-server code into the main core. Python -m aspen is convenient enough.

**Comment by whit537** [comment]
> I thinks that's became pretty obvious in Python world

Yeah, I can see that.

> I also don't like that Website inherits from Configuration instead of encapsulating it.

I agree, but that's a separate issue: reticketed as #444 and added to the roadmap (#357).

> I vote no Website.run() because it moves WSGI-server code into the main core. Python -m aspen is convenient enough.

Too late. We already have [WSGI-server code in the main core](https://github.com/gratipay/aspen-python/blob/0.37/aspen/__main__.py).

> For me publishing means `compile and upload`, or `release draft to public`.

Here it means "put it on the network." I chose `publish` over `mount`. How about just `serve`?

```python
from aspen import serve, Website

website = Website()

if __name__ == '__main__':
    serve(website)
```

> It names it `app`, but it is WSGI application.

Right. `Website` instances are also WSGI applications. ;-)

**Comment by pjz** [comment]
C'mon, we did this already - down this path lies engines and etc.  __main__ is the *only* WSGI server code we have in the app, and it's just as a convenience.  It's where it won't bother anyone who doesn't use it (unlike if it's on the main `Website` object).

**Comment by whit537** [comment]
@pjz Check my implementation in #445. It's not on the main `Website` object.

**Comment by whit537** [comment]
@pjz And against "down this path lies engines and etc.," consider the example of Flask and Django. They both provide this convenience, and as @techtonik suggests: "I thinks that's became pretty obvious in Python world [that this is not a high-performance server], but could be explained once more in docstring."

**Comment by pjz** [comment]
alright fine. As soon as it passes tests.

**Comment by whit537** [comment]
Done, though because of #446 I dropped back to:

```python
from aspen import serve, website

website = website.Website()

if __name__ == '__main__':
    serve(website)
```

**Comment by techtonik** [comment]
@whit537 note that `website = website.Website()` is not a valid WSGI app anymore.

**Comment by whit537** [comment]
> note that `website = website.Website()` is not a valid WSGI app anymore.

Why not?

**Comment by techtonik** [comment]
Because by default webservers look for `application` name.

**Comment by pjz** [comment]
what webservers? Link to docs, please.

**Comment by techtonik** [comment]
https://code.google.com/p/modwsgi/wiki/QuickConfigurationGuide#WSGI_Application_Script_File

**Comment by techtonik** [comment]
> As you can see, it is composed of a single Python function. It is called “application” as this is default function that the uWSGI Python loader will search for (but you can obviously customize it).

https://uwsgi-docs.readthedocs.org/en/latest/WSGIquickstart.html#the-first-wsgi-application

**Comment by techtonik** [comment]
> Gunicorn will look for a WSGI callable named application if not specified. 

https://gunicorn-docs.readthedocs.org/en/latest/run.html#django

**Comment by techtonik** [comment]
Need more? =)

**Comment by whit537** [comment]
> `website = website.Website()` is not a valid WSGI app anymore,
> Because by default webservers look for `application` name.

@techtonik Bound variable name is a bad test for the validity of a WSGI application, because all three of the servers you cite will, in fact, have no problem using a `Website` instance bound to a `website` variable as a WSGI application, because each has simple mechanisms for specifying a WSGI app named something other than `application`. In any case, the matter is irrelevant for Aspen, because you're free to bind your `Website` instance to whatever variable name you like: that's a nice side-benefit of the fact that **Aspen is a library**.

**Comment by whit537** [comment]
> In any case, the matter is irrelevant for Aspen [...]

Actually, the one place it's relevant is in `aspen.wsgi` ... #449.

**Comment by techtonik** [comment]
>  each has a simple mechanism for specifying a WSGI app named something other than application

Not sure about the `simple`. At least on one of those it is not.

**Comment by techtonik** [comment]
> Actually, the one place it's relevant is in aspen.wsgi ... #449.

Ok. Didn't know that `aspen.wsgi` exists.

**Comment by whit537** [comment]
> Didn't know that `aspen.wsgi` exists.

Sounds like someone hasn't [read the fine :book:](http://aspen.io/deployment/), nor [used a :mag: engine](https://www.google.com/search?q=aspen+wsgi). ;-)

**Comment by whit537** [comment]
Easing mod_wsgi configuration reticketed as #452, based on the search results I just looked at. :-)

**Comment by techtonik** [comment]
Well, at first I was thinking that `aspen` is just a `simplates` engine like Jinja2. So I didn't think it requires to be a WSGI app. And after all that problem was deep in the stack of the bugs I was trying to unwind, and in this situation the deficit of attention just becomes worse. =)
