### ISSUE TITLE
set up CI for Windows

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#442]
Travis doesn't offer CI for Windows. Looks like our best bet is [AppVeyor](http://www.appveyor.com/). I've signed up for an account there.

**Comment by whit537** [comment]
Here's [an example `appveyor.yml`](https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml).

**Comment by whit537** [comment]
From [this demo project](https://github.com/ogrisel/python-appveyor-demo).

> This project is meant to document a minimalistic yet working example to help other Python project maintainers.

**Comment by whit537** [comment]
Wanna work on this, @techtonik? :)

**Comment by whit537** [comment]
Looks like they're using [Conda](http://conda.pydata.org/):

Conda is a cross-platform, Python-agnostic binary package manager.

**Comment by techtonik** [comment]
What needs to be run there? Right now the main problem for usage on Windows is Misaka, which doesn't have a compiled extension for Windows - https://pypi.python.org/pypi/misaka

**Comment by techtonik** [comment]
I setup AppVeyour for testing SCons https://ci.appveyor.com/project/techtonik/scons/ and building regal https://ci.appveyor.com/project/techtonik/regal/
