### ISSUE TITLE
see if we like this advice about making Python libraries

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#448]
http://axialcorps.com/2013/08/29/5-simple-rules-for-building-great-python-packages/

**Comment by pjz** [comment]
Sure; make actionable items into standalone issues; #454 is a start.

**Comment by whit537** [comment]
Reticketed only using __init__.py for imports as #456, and consolidated exceptions into one module in 880440b577aa2cbf20c86e27249bac9c72de02e2.
