### ISSUE TITLE
truly remove `request.fs`

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen-python#450]
https://github.com/gratipay/inside.gratipay.com/pull/263#issuecomment-113667650

**Comment by techtonik** [comment]
And it is not clear what is the replacement.

**Comment by whit537** [comment]
Good find! Fixed in #451.

> It should be added to Changelog.md

I think we will have to have you help us write the Changelog entry for our next release. :-)

**Comment by techtonik** [comment]
> I think we will have to have you help us write the Changelog entry for our next release. :-)

No problem. =) But you need to tell the the text.

**Comment by techtonik** [comment]
Hi @pjz Is it possible to wrap a release, so that I can update dependencies in `requirements.txt` for inside.gp?
