### ISSUE TITLE
functions in simplates behave unintuitively wrt scope

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#462]
Introduced in #427.

This fails:

```python
bar = 'baz'
def foo()
    return bar
[---] text/html
```

This succeeds:

```python
bar = 'baz'
def foo()
    global bar
    return bar
[---] text/html
{{ foo() }}
```

**Comment by pjz** [comment]
How's it fail? Got a failing test?

**Comment by pjz** [comment]
Hm. I'm not sure this is fixable wrt #427. Oh, hm, maybe if `state` is a copy of the real state dict instead of a pointer to it ?  Then it won't bleed into the algorithm state.

**Comment by whit537** [comment]
Bit of a snafu over here.

https://github.com/gratipay/gratipay.com/commit/efec253b2f336e3cc07093f2a03cf435bc840c67

**Comment by whit537** [comment]
This function is broken as well:

https://github.com/gratipay/gratipay.com/blob/1860/gratipay/utils/i18n.py#L205-L228

**Comment by whit537** [comment]
:-(

**Comment by whit537** [comment]
> If two expressions are given, they are used for the global and local variables, respectively. If provided, locals can be any mapping object. Remember that at module level, globals and locals are the same dictionary. If two separate objects are given as globals and locals, the code will be executed as if it were embedded in a class definition.

https://docs.python.org/2.7/reference/simple_stmts.html#exec

**Comment by whit537** [comment]
PR in #463. Afaict it fixes https://github.com/gratipay/aspen-python/issues/462#issuecomment-116888775 but not https://github.com/gratipay/aspen-python/issues/462#issuecomment-116889347, so we may need another PR ...
