### ISSUE TITLE
http://aspen.io/core-algorithms/ needs improvement

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen-python#464]
The page contains just a list of function prototypes and a link to algorithm.py docs without actually explaining much. The more useful piece of docs would be to link the following phrase `If you want to modify Aspen's behavior ` with "If you want to **modify**" linking to the actual example of modification (in Gratipay code or somethere else) and "**Aspen's behavior**" to actual chain of Aspen algorithm configuration.

**Comment by techtonik** [comment]
In https://github.com/gratipay/aspen-python/blob/8da0b567ac5e1fa93b3bbfc7a35aecf91d36939f/aspen/algorithms/website.py `the functions defined in this present module are executed in the order they're defined here`. ??? This is very magical. Who does the chaining? It can not be automatic, or can it?

**Comment by techtonik** [comment]
http://algorithm-py.readthedocs.org/en/1.0.0/#algorithm.Algorithm.from_dotted_name - this function is used to parse the file, but it refers to confusing concept of `algorithm definition module`.

**Comment by pjz** [comment]
Fixed in #467
