### ISSUE TITLE
hold July call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#472]
Currently scheduled for 9am US/Eastern on July 9.

**Comment by whit537** [comment]
Ping @pjz et al. 35 minutes, ya?

**Comment by pjz** [comment]
:+1:

**Comment by whit537** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYdq8JeEs7MBkvlEqvlYZWNpPzVNn-1pzsIY-ddqDaphMQ7pBQ

**Comment by whit537** [comment]
Watch link: https://www.youtube.com/watch?v=2wEJBOIwlwY.

**Comment by whit537** [comment]
Flask's config docs: http://flask.pocoo.org/docs/0.10/config/

**Comment by whit537** [comment]
!m @pjz

**Comment by whit537** [comment]
Next call August 13.
