### ISSUE TITLE
hold August 2015 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#474]
July: https://github.com/gratipay/aspen-python/issues/472.

**Comment by whit537** [comment]
August 13

**Comment by whit537** [comment]
Still on for Thursday at 9am US/Eastern, @pjz @techtonik et al.? We have a lot to discuss this month. :-)

**Comment by pjz** [comment]
Yes

**Comment by whit537** [comment]
10 minutes, @pjz?

**Comment by pjz** [comment]
yup

**Comment by pjz** [comment]
??

**Comment by whit537** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYevZ4lYVipAjEUHxjM7VEL1XpcVBozM4VDwcd_fRXxmeQRvKg

**Comment by whit537** [comment]
Watch here: https://www.youtube.com/watch?v=tUuHtr4AgWw.

**Comment by whit537** [comment]
@pjz points to http://click.pocoo.org/ for arg parsing.

**Comment by whit537** [comment]
Our Python libraries: https://github.com/gratipay/?query=.py.

**Comment by whit537** [comment]
!m @pjz

**Comment by techtonik** [comment]
Well, I am still overburdened with little plans ideas and things to do. Pretty big mess in my head to arrange anything.
