### ISSUE TITLE
Nuke old engine modules from pypi

### ISSUE THREAD

**Issue by pjz** [gratipay/aspen-python#475]
`aspen-{diesel, eventlet, gevent, rocket, twisted}` should all be removed from pypi, no?

**Comment by whit537** [comment]
Yes.

**Comment by whit537** [comment]
@pjz Do you have access to accomplish that?

**Comment by pjz** [comment]
yes

**Comment by pjz** [comment]
aspen-pants is also just an Engine, so nuking it as well.

**Comment by pjz** [comment]
aspen-cherrypy is also just an Engine, so nuking it as well.

**Comment by pjz** [comment]
Okay, all the ones left are valid plugins.

**Comment by whit537** [comment]
!m @pjz
