### ISSUE TITLE
Add links to AppVeyor status

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen-python#484]
To http://aspen.io/ and to GitHub page. This requires API key and I don't know where to get it.

**Comment by whit537** [comment]
AppVeyor is supported by http://shields.io/, without requiring an API key:

```markdown
[![AppVeyor](https://img.shields.io/appveyor/ci/gratipay/aspen-python.svg)](https://ci.appveyor.com/project/gratipay/aspen-python)
```

[![AppVeyor](https://img.shields.io/appveyor/ci/gratipay/aspen-python.svg)](https://ci.appveyor.com/project/gratipay/aspen-python)

**Comment by techtonik** [comment]
[![AppVeyor](https://img.shields.io/appveyor/ci/gratipay/aspen-python.svg "AppVeyor Build Result") ](https://ci.appveyor.com/project/gratipay/aspen-python)

[ ![AppVeyor](https://img.shields.io/appveyor/ci/gratipay/aspen-python.svg "AppVeyor Build Result") ](https://ci.appveyor.com/project/gratipay/aspen-python)

**Comment by techtonik** [comment]
On the second look at http://www.appveyor.com/docs/status-badges API key is not required for public repositories, so it is possible to use official badge with a nice logo. 

    [![AppVeyor](https://ci.appveyor.com/api/projects/status/github/gratipay/aspen-python?branch=master&svg=true "AppVeyor Build Result") ](https://ci.appveyor.com/project/gratipay/aspen-python)

[![AppVeyor](https://ci.appveyor.com/api/projects/status/github/gratipay/aspen-python?branch=master&svg=true "AppVeyor Build Result") ](https://ci.appveyor.com/project/gratipay/aspen-python)

**Comment by whit537** [comment]
@techtonik I think we should use the Shields version, because standardization is the reason that Shields exists, and [Shields is a Gratipay project](http://blog.gittip.com/post/59396458675/gittip-has-acquired-shields/). :dancer:

**Comment by pjz** [comment]
I did a first pass at this on #482 since this PR kind of depends on it.

**Comment by pjz** [comment]
Fixed in #482

**Comment by techtonik** [comment]
@whit537 I am not sure that shields doesn't cache results more than necessary.

**Comment by whit537** [comment]
@techtonik Then make an issue/PR over there.
